### ISSUE TITLE
Add New button, form displayed for Visibility Status even if required Permissions Pro module not active

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#64]
With PublishPress Permissions installed, I try to add a new Visibility status

I get to this screen:
<img width="906" alt="Screenshot 2023-10-18 at 3 02 44 PM" src="https://github.com/publishpress/publishpress-statuses/assets/3868028/ced523a8-219d-40a6-ba33-04272572d441">

Then next: "Could not add status: Invalid taxonomy."
<img width="826" alt="Screenshot 2023-10-18 at 3 04 47 PM" src="https://github.com/publishpress/publishpress-statuses/assets/3868028/97c0e58a-7fbf-4377-8260-556ed36003a6">

**Comment by agapetry** [comment]
This is resolved by a Permissions Pro update

**Comment by stevejburge** [comment]
Still seeing this with these releases:
![Screenshot 2023-12-14 at 10 30 12 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/f56873e8-6f31-4029-a686-74d1f5a999a5)

**Comment by agapetry** [comment]
@stevejburge You need to enable Permissions > Settings > Statuses > Visibility Statuses: 

![image](https://github.com/publishpress/publishpress-statuses/assets/43488774/d6d0041b-1520-4e70-8a92-5b89a367d6bf)

This will be an easy fix to suppress the Add New button based on that setting, not just Permissions Pro Status Control module activation.

When I get back tomorrow, I'll also add an explanatory link on the Statuses > Visibility tab if Visibility Statuses are note enabled.

**Comment by stevejburge** [comment]
Thanks. Yes, suppressing the button sounds like the best idea
